#pragma once
#define BIG_MAT_COLS 20
#define BIG_MAT_ROWS 3
#define SMALL_MAT_SIZE 4
#define SMALL_SIZE (SMALL_MAT_SIZE*SMALL_MAT_SIZE)
#define BIG_SIZE (BIG_MAT_ROWS * BIG_MAT_COLS)
#define LEN (SMALL_SIZE+SMALL_MAT_SIZE)
